// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

//Declare initial values

var i = 1;
var previous_1 = 1;
var previous_2 = 1;
var sum_num = 0;

while (i <= 4000000) {

  //If the Fibonacci number is even, add it to the sum
  if (i % 2 === 0) {
    sum_num = sum_num + i;
  };

  //Reset values after adding
  previous_2 = previous_1;
  previous_1 = i;
  i = previous_1 + previous_2;
};

console.log(sum_num);

//TODO: utlize an array instead
